-
  name: 'logout'
  uriPattern: 'felogin/logout'
  defaults:
    '@package': 'NeosRulez.FrontendLogin'
    '@controller': 'Login'
    '@action': 'logout'
  appendExceedingArguments: true
-
  name: 'create user'
  uriPattern: 'felogin/create'
  defaults:
    '@package': 'NeosRulez.FrontendLogin'
    '@controller': 'User'
    '@action': 'create'
  appendExceedingArguments: true
-
  name: 'update user'
  uriPattern: 'felogin/update'
  defaults:
    '@package': 'NeosRulez.FrontendLogin'
    '@controller': 'User'
    '@action': 'update'
  appendExceedingArguments: true
-
  name: 'reset users password'
  uriPattern: 'felogin/reset'
  defaults:
    '@package': 'NeosRulez.FrontendLogin'
    '@controller': 'User'
    '@action': 'reset'
  appendExceedingArguments: true
-
  name: 'reset users password'
  uriPattern: 'felogin/updatepassword'
  defaults:
    '@package': 'NeosRulez.FrontendLogin'
    '@controller': 'User'
    '@action': 'updatePassword'
  appendExceedingArguments: true
