-
  name: 'Frontend Login Form'
  uriPattern: 'felogin(/{@action}).{@format}'
  defaults:
    '@package': 'NeosRulez.FrontendLogin'
    '@controller': 'Authentication'
    '@format': 'html'
    '@action': 'authenticate'
  appendExceedingArguments: true
-
  name: 'logout'
  uriPattern: 'logout'
  defaults:
    '@package': 'NeosRulez.FrontendLogin'
    '@controller': 'Login'
    '@format': 'html'
    '@action': 'logout'
  appendExceedingArguments: true