Neos:
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Neos.Neos.FrontendLogin:NeosBackend':
                pattern: NeosRulez\FrontendLogin\Security\NeosRequestPattern
          'NeosRulez.FrontendLogin:NeosFrontend':
            provider: PersistedUsernamePasswordProvider
            requestPatterns:
              'NeosRulez.FrontendLogin:NeosFrontend':
                pattern: NeosRulez\FrontendLogin\Security\NeosRequestPattern
                patternOptions:
                  matchFrontend: true
    mvc:
      routes:
        'NeosRulez.FrontendLogin': true
  Neos:
    eventLog:
      enabled: true
    userInterface:
      translation:
        autoInclude:
          NeosRulez.FrontendLogin:
            - Main
            - 'NodeTypes/*'
      defaultLanguage: 'de'
    nodeTypes:
      groups:
        neosrulez_frontendlogin:
          position: 'end'
          label: NeosRulez.FrontendLogin:Main:felogin
    fusion:
      autoInclude:
        NeosRulez.FrontendLogin: true
    modules:
      frontendlogin:
        label: 'Frontend Login'
        controller: '\Neos\Neos\Controller\Module\ManagementController'
        description: 'Benutzer und Gruppen f端r gesch端tzten Bereich verwalten'
        icon: 'fas fa-unlock'
        resource: 'Neos_Neos_Backend_Module_Management'
        submodules:
          user:
            label: 'Benutzer'
            controller: '\NeosRulez\FrontendLogin\Controller\UserController'
            description: 'Benutzer f端r gesch端tzten Bereich verwalten'
            icon: 'fas fa-user'
            actions:
              index:
                label: 'Benutzer verwalten'
                title: 'Benutzer verwalten'